export const ASSET_KEYS = {
  batteryDead: 'battery-dead',
  batteryFresh: 'battery-fresh',
  batteryMachineDead: 'battery-machine-dead',
  batteryMachineFull: 'battery-machine-full',
  batteryMachineOpen: 'battery-machine-open',
  batterySupply: 'battery-supply',
  beacon: 'scaffold-beacon',
  crackBlocked: 'crack-blocked',
  crackPatched: 'crack-patched',
  crackWarning: 'crack-warning',
  discardBin: 'discard-bin',
  emblem: 'scaffold-emblem',
  gearGrinding: 'gear-grinding',
  gearHealthy: 'gear-healthy',
  gearNeedsOil: 'gear-needs-oil',
  oilPump: 'oil-pump',
  player: 'prototype-player',
  repairPlate: 'repair-plate',
  repairPlateSupply: 'repair-plate-supply',
} as const;
